### ISSUE TITLE
NewTitle function not working any more

### ISSUE THREAD

**Issue by dda119141** [StalkR/imdb#13]
Hi

It seems, that the call

    `title, err := imdb.SearchTitle(client, movie_name)`

if returning an error:

    `imdb: parsing error: id`

Tested with latest version v1.0.15

Maybe it is due to an imdb server update ?

Cheers

**Comment by StalkR** [comment]
Hi,

Which movie name are you trying? maybe there's something specific to it and it can't handle it.

The tests all still work for me, so it could also just be the IP you're trying from. Try another, and make sure not to make too many requests or you risk getting rejected again potentially.

If you get me the actual response (status + contents) I can try to identify and make a more helpful error.

I'm already identifying 403 (https://github.com/StalkR/imdb/commit/252fb81dc992007144000dd17e099d81c9133620), so must be something else.

**Comment by dda119141** [comment]
The title's names are "saloum" or "Shrin Ultraman"

The call imdb.searchTitle works well. Sorry I wrongly described the issue. 
It is about the operation imdb.NewTitle(client, title[0].id).

'
title, err := imdb.SearchTitle(client, movie_name)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Search title Error: %v\n", err)
		return imdbRating{}, err
	}
	if len(title) == 0 {
		fmt.Fprintf(os.Stderr, "title length Not found\n.")
		return imdbRating{}, fmt.Errorf("title error")
	}

	got, err := imdb.NewTitle(client, title[0].ID)
	if err != nil {
		fmt.Fprintf(os.Stderr, "New Title Not found: %s.\n", title[0].Name)
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		//fmt.Printf("title Rating: %d\n", title[0].RatingCount)
		//fmt.Printf("title ID: %s", title[0].ID)
		return imdbRating{}, fmt.Errorf("new title error")
	}
'

**Comment by StalkR** [comment]
I confirm it works for me using the official example (https://github.com/StalkR/imdb/blob/master/examples/imdb.go) which does the same, a `SearchTitle` then `NewTitle` with the title ID.

```
$ go run imdb.go -- 'saloum'
Saloum (2022) - Action, Horror, Thriller - Jean Luc Herbulot - Yann Gael, Evelyne Ily Juhen, Roger Sallah - 1h24m - 6.2 - https://www.imdb.com/title/tt10756184
```

Note the [custom transport](https://github.com/StalkR/imdb/blob/master/examples/imdb.go#L42) used in the example to avoid triggering AWS WAF, but I would have expected a forbidden error if not.

I don't know why it errors with a `parsing error: id` for you. Can you log the http request/response and share? Either it's a website update and I need to adjust parsing, or it's an error where I can respond a better message.

**Comment by dda119141** [comment]
Hmm interesting when I execute
      
go run imdb.go -- 'saloum'
      
I get this:
      
Error: imdb: parsing error: languages
exit status 2
      

So the is something missing in my environment I guess ?

**Comment by dda119141** [comment]
Hi,

I found the issue. I picked up the wrong version.

the version v.1.0.15 fixed the issue.

Thanks again for the support!

Cheers

**Comment by StalkR** [comment]
Great! Yes always take latest :)
