### ISSUE TITLE
imdb: parsing error: id

### ISSUE THREAD

**Issue by shingsam** [StalkR/imdb#5]
Hi, i have issue parsing error id when i get movie by IMDB id.

**Comment by shingsam** [comment]
Ok, i'll wait the update.
Can u added more details about Movie ? Like this http://www.theimdbapi.org/api/movie?movie_id=tt0133093

**Comment by StalkR** [comment]
Fixed: https://movie-db-api.appspot.com/title/tt0133093

As for more details, it's possible but it's work and I don't feel like it because I don't need more details. Feel free to send a pull request though!

**Comment by shingsam** [comment]
Ok, thankyou. :1st_place_medal:
